# Generated by Django 4.1.4 on 2022-12-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("super_hero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeSuperHero",
            fields=[
                (
                    "superhero_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="super_hero.superhero",
                    ),
                ),
                ("from_anime", models.CharField(max_length=255)),
            ],
            bases=("super_hero.superhero",),
        ),
        migrations.CreateModel(
            name="MarvelSuperHero",
            fields=[
                (
                    "superhero_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="super_hero.superhero",
                    ),
                ),
                ("from_film", models.CharField(max_length=255)),
            ],
            bases=("super_hero.superhero",),
        ),
        migrations.AlterField(
            model_name="superhero",
            name="strength",
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
