# Generated by Django 4.1.4 on 2022-12-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("super_hero", "0002_animesuperhero_marvelsuperhero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DCSuperHero",
            fields=[
                (
                    "marvelsuperhero_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="super_hero.marvelsuperhero",
                    ),
                ),
            ],
            bases=("super_hero.marvelsuperhero",),
        ),
    ]
